### ISSUE TITLE
typings mismatch

### ISSUE THREAD

**Issue by goleafs** [SenyaMur/ag-grid-odata#27]
Is it possible the npm package is referencing older version of ag-grid?
I'm finding some errors, I think maybe ag-grid changed how to reference it.

e.g.

Error: node_modules/ag-grid-odata/build/OdataProvider.d.ts:2:10 - error TS2305: Module '"@ag-grid-enterprise/all-modules"' has no exported member 'IServerSideGetRowsParams'.

and for example, in the types.d.ts this does not compile:
import { ColumnVO } from '@ag-grid-community/all-modules';
but this is ok:
import { ColumnVO } from 'ag-grid-community';

**Comment by SenyaMur** [comment]
Do you mean this line https://github.com/SenyaMur/ag-grid-odata/blob/master/src/OdataProvider.ts#L5 and next too?

**Comment by SenyaMur** [comment]
Hi, @goleafs. I published new version [v1.0.27](https://www.npmjs.com/package/ag-grid-odata/v/1.0.27) where using ag-grid-community and  ag-grid-enterprise. 
And i update examples
https://codesandbox.io/s/ag-grid-odata-angular-ls3lj?file=/src/app/app.component.ts

**Comment by goleafs** [comment]
Looks like there is still an issue when trying to build:

Error: node_modules/ag-grid-odata/build/OdataProvider.d.ts:85:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library which declares OdataProvider has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

85 export declare class OdataProvider implements OdataProviderOptions {
                        ~~~~~~~~~~~~~

**Comment by goleafs** [comment]
Thanks for the updates @SenyaMur I got it working in our app.
We had authenticated endpoints so had to call the odata endpoint differently but it seems ok now.
Great little package you made, thank you!
I am noticing a few things aren't working proper (like column filters) but I have not had a chance to look into it yet.  Will continue with feedback as we get a chance to trial it out.  Cheers!

**Comment by SenyaMur** [comment]
Great, @goleafs! I wish you good luck.
